### ISSUE TITLE
Uncaught TypeError: Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by WLCPereira** [illBeRoy/react-electron-browser-window#1]
There is an error on this line!
title: _react2.default.PropTypes.string.

**Comment by illBeRoy** [comment]
Hi! This was addressed in the following commit: https://github.com/illBeRoy/react-electron-browser-window/commit/445b82cd7a0ecd27756e06c5d8be6a048d7e119a

Please update to version 0.1.2!

The gist is that I moved it to use the `prop-types` lib instead of the built in react one.

(sorry for the long delay, for some reason I wasn't watching the repo!)

Please let me know if the problem was solved for you (given that it's still relevant of course ;))
