### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by wQwRtaufxJw7UFLCXzXz** [illBeRoy/react-electron-browser-window#2]
Getting this error on the deprecated function when I add your library to my project.

![screen shot 2018-04-04 at 3 07 02 pm](https://user-images.githubusercontent.com/249497/38337379-e7b5f252-3819-11e8-817d-bb29949c5bdc.png)

**Comment by mengfoobar** [comment]
yeah i got the same thing as @dpgailey

**Comment by illBeRoy** [comment]
Hello! First of all, sorry for the late response.

When you are using webpack for your app, it overrides all `require` statements, unless told otherwise. This means that you cannot use "native" modules, such as filesystem or electron modules, since they cannot be bundled into javascript.

Because of that, electron will not boot for you inside the browser, so `react-electron-browser-window` cannot be initialized.

I would suggest removing webpack all together: since electron provides you with native `require` capabilities, and since you're serving your assets locally, in most cases you do not need webpack when working with electron at all.

If you **must** use webpack, i would suggest taking a look at [npm/electron-webpack](https://www.npmjs.com/package/electron-webpack). It will solve the problem with importing electron, and will make the code work.

Good luck!
